PreCommit:
  RuboCop:
    enabled: true
    command: ["bundle", "exec", "rubocop", "--force-exclusion"]
    on_warn: fail

  TrailingWhitespace:
    enabled: true

PrePush:
  Migrations:
    enabled: true

CommitMsg:
  TextWidth:
    enabled: true
    max: 60
    message: "Commit message lines should not exceed 60 characters"
